project_id = "service-center-tbt-phone-tech"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://service-center-tbt-phone-tech.vercel.app"]

[db]
major_version = 15
